# Generated by Django 2.2 on 2019-04-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='birds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('colour', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=1000)),
            ],
        ),
    ]
