# Generated by Django 2.2 on 2019-04-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='birds',
            new_name='birds_info',
        ),
    ]
