# Generated by Django 2.2 on 2019-04-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibis', '0002_auto_20190405_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='birds_info',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_ibis/images'),
        ),
    ]
