# Generated by Django 2.2 on 2019-04-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibis', '0004_auto_20190406_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds_info',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
