# Generated by Django 2.2 on 2019-04-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibis', '0005_auto_20190407_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds_info',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_ibis/images'),
        ),
    ]
