# Generated by Django 2.2 on 2019-04-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibis', '0006_auto_20190407_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds_info',
            name='info',
            field=models.TextField(max_length=1000),
        ),
    ]
